"""Local monopoly-core bridge service for Potato Finance PWA.

Run:
  pip install monopoly-core fastapi uvicorn python-multipart
  uvicorn tools.monopoly_bridge:app --host 127.0.0.1 --port 8765
"""

from __future__ import annotations

import csv
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from fastapi import FastAPI, File, Header, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="Potato Finance monopoly-core bridge")

allowed_origins = [origin.strip() for origin in os.getenv("BRIDGE_ALLOWED_ORIGINS", "*").split(",") if origin.strip()]
app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins or ["*"],
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

BRIDGE_API_KEY = os.getenv("BRIDGE_API_KEY", "").strip()
MAX_FILE_MB = int(os.getenv("MAX_FILE_MB", "15"))


def _pick(row: dict[str, str], keys: list[str], default: str = "") -> str:
    lowered = {k.lower(): v for k, v in row.items()}
    for key in keys:
        if key in lowered and lowered[key] not in (None, ""):
            return lowered[key]
    return default


def _convert_rows(csv_path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with csv_path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            description = _pick(row, ["description", "merchant", "remarks", "transaction description"])
            posted_date = _pick(row, ["posted_date", "date", "transaction date", "post date"])
            amount = _pick(row, ["amount", "transaction amount", "amt"])
            debit = _pick(row, ["debit", "withdrawal", "dr"])
            credit = _pick(row, ["credit", "deposit", "cr"])
            currency = _pick(row, ["currency", "ccy"], "SGD")

            rows.append(
                {
                    "source": "monopoly-core",
                    "account_name": _pick(row, ["account", "account_name", "card", "source"], "monopoly-core"),
                    "posted_date": posted_date,
                    "description": description,
                    "amount": amount,
                    "currency": currency,
                    "debit": debit,
                    "credit": credit,
                    "raw_text": " | ".join(f"{k}:{v}" for k, v in row.items() if v),
                    "confidence": 0.93,
                }
            )
    return rows


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/parse")
async def parse_statement(file: UploadFile = File(...), x_api_key: str | None = Header(default=None)) -> dict[str, Any]:
    if BRIDGE_API_KEY and x_api_key != BRIDGE_API_KEY:
        raise HTTPException(status_code=401, detail='Invalid API key.')

    suffix = Path(file.filename or "statement.pdf").suffix or ".pdf"
    if suffix.lower() != ".pdf":
        raise HTTPException(status_code=400, detail="Only PDF uploads are supported for this endpoint.")

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        input_path = tmp_path / "statement.pdf"
        output_dir = tmp_path / "out"
        output_dir.mkdir(parents=True, exist_ok=True)

        content = await file.read()
        if len(content) > MAX_FILE_MB * 1024 * 1024:
            raise HTTPException(status_code=413, detail=f"File too large. Max {MAX_FILE_MB}MB")

        input_path.write_bytes(content)

        cmd = [
            "monopoly",
            str(input_path),
            "--output",
            str(output_dir),
            "--preserve-filename",
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise HTTPException(status_code=500, detail=f"monopoly-core failed: {result.stderr.strip()}")

        csv_files = sorted(output_dir.glob("*.csv"))
        if not csv_files:
            raise HTTPException(status_code=500, detail="No CSV output generated by monopoly-core.")

        rows = _convert_rows(csv_files[0])
        return {"rows": rows, "csv_file": csv_files[0].name}
